version: '3'
services:
     nginx:
          depends_on:
               - prep
          image: 'nginx:1.17.3'
          container_name: 'nginx'
          volumes:
               - ./nginx/nginx.conf:/etc/nginx/nginx.conf
               - ./nginx/access_lists/:/etc/nginx/access_lists/
               - ./nginx/log/:/var/log/nginx/
          ports:
               - 9000:9000
               - 7100:7100
          external_links:
               - prep
          restart: always

     prep:
          image: '{{ image }}'
          container_name: 'prep'
          environment: {% if network_name == 'mainnet' %}

               NETWORK_ENV: "mainnet"
               LOG_OUTPUT_TYPE: "file"
               SWITCH_BH_VERSION3: "10324749"
               CERT_PATH: "/cert"
               LOOPCHAIN_LOG_LEVEL: "DEBUG"
               ICON_LOG_LEVEL: "DEBUG"
               FASTEST_START: "yes"{% else %}

               CERT_PATH: "/cert"
               LOOPCHAIN_LOG_LEVEL: "DEBUG"
               ICON_LOG_LEVEL: "DEBUG"
               FASTEST_START: "yes"{% endif %}

               PRIVATE_KEY_FILENAME: "{{ keystore_path | basename }}"
               PRIVATE_PASSWORD: "{{ keystore_password }}"
               {% if citizen_ip is defined %}ENDPOINT_URL: "{{ ("http://" + citizen_ip + ":9000") }}"{% endif %}

          cap_add:
               - SYS_TIME
          volumes:
               - ./data:/data
               - ./cert:/cert
          expose:
               - '9000'
               - '7100'
          restart: always
